### PR TITLE
Explicity mention path in require

### PR DESCRIPTION
**Pull request by rudra101**
This was basically a workaround for deploying some code to AWS over sls.

Please ignore these changes if they are not well thought out.

### CODE REVIEW

**Comment by benjamine** [comment]
sorry, can you provide some explanation of what is this for? link to an existing issue?
this change would make browserify include files in the bundle that it shouldn't.

**Comment by d4rkr00t** [comment]
Just leaving it here https://github.com/benjamine/jsondiffpatch/issues/172

**Comment by darkdigitaldream** [comment]
This one is important in certain environments. I am using jsonDiffPatch in a web worker written in typescript and packaged with webpack. Without this fix, I get the console warning:

WARNING in ./~/jsondiffpatch/src/main.js
61:19-47 Critical dependency: the request of a dependency is an expression

and at runtime I get the error:
Uncaught Error: Cannot find module "."

**Comment by Stetzon** [comment]
+1

**Comment by cooperka** [comment]
@benjamine any updates on this? See issue #172 for more details.

**Comment by pSchaub** [comment]
Please merge this as soon as possible. The error with webpack bundling is annoying.

**Comment by benjamine** [comment]
@cooperka , @pSchaub read my first comment. this isn't a bug, but intentionally excluding modules from web bundle. the right solution is to use `package.json` to exclude those modules (there's a syntax to do that that works both with webpack and browserify)

**Comment by pSchaub** [comment]
@benjamine Then please add this information to the README

**Comment by benjamine** [comment]
@pSchaub it's OK that is an implementation detail, don't think it belongs there.
there is now pull request #207 which follows the approach I mentioned above, haven't had time to test that yet but considering that I'm closing this one, thanks for helping me troubleshoot this!
will send an update when this issue is solved.

**Comment by benjamine** [comment]
I just released a migration to `rollup` (used a similar approach as facebook's react lib), which implies a very different bundling setup.
now the package has a `/dist` folder with different bundles for UMD, commonjs (regular node.js), and ES modules (modern ES), given the info in package.json, node and all web bundlers should pick the right one automically 🎉.

I released this as `jsondiffpatch@0.3.1`, ie. it's a semver breaking change only because I decided to drop support for node < v4.8.0, but there are no API changes.
Please test it out and let me know if you have any problems (particular interested in results with different web bundlers)

**Pull request closed without merging**
