### PR TITLE
update travis config to include node 4, 5, 0.11, 0.12

### PR DESCRIPTION
**Pull request by renewooller**

### CODE REVIEW

**Comment by benjamine** [comment]
thanks @renewooller !, there seems to be an error with node.js 5,
until/unless that's green, can you remove that one? 
later I'd try to add nodejs 6, I heard travis already supports it :)

**Comment by renewooller** [comment]
And thanks for the lib! Looking forward to trying it. The red there is a little deceptive - all the test are passing, it's only the bundle / minification which is failing. Not sure if there's another easy way to fix that?

**Comment by benjamine** [comment]
@renewooller I'm not sure, it sounds like a dependency's compatiblity with node 5, the error is not very descriptive unfortunately.

**Comment by benjamine** [comment]
after v0.3.2, travis is testing in node 4, 8, and 9, so I think I can close this one, thanks!

**Pull request closed without merging**
