### PR TITLE
use diff-match-patch dependency

### PR DESCRIPTION
**Pull request by patrick-webs**
An explicit dependency on the diff-match-patch library is introduced so
that when requiring this library through NPM it doesn't result in the
error "text diff_match_patch library not found" after creating a
browserify bundle (because browserify doesn't find the require statement
embedded inside a conditional).

PR includes a lot of changes in the public/ folder that seemed to be introduced when I ran the build. I can remove these changes and only include package.json and the src/ changes if that's better.

### CODE REVIEW

**Comment by MJefferson** [comment]
Hey, is there any reason why this PR hasn't been merged in yet? My team is running into this error as well.

**Comment by benjamine** [comment]
Hi, @MJefferson there are a few reasons:
- I didn't have time to review it before
- I haven't yet reproduced this issue, I use this library as a dependency in other projects that use browserify and they seem to work fine, can you provide reproduction steps?
- codacy check failed (var dmp is defined twice)
- this PR removes `mocha.js` and `mocha.css` files from the build folder, is there a reason for that?
- I wouldn't like to have 2 different versions of that dependency load in different circumstances, and this seem to be allowing that, and based on throwing an exception.

**Comment by area** [comment]
I've been seeing this issue as well, but I've never tried to use browserify before, so I'm not really sure what would constitute a MWE.

I ran into this by trying to use https://github.com/janmonschke/diffsync , including when using the standalone version available at https://wzrd.in/standalone/diffsync (which is linked to from the diffsync README).

Tagging @janmonschke in the hope he can shed some light.

**Comment by nonplus** [comment]
+1  Ran into the same problem when trying to use it with jspm.

**Comment by atifsyedali** [comment]
To reproduce, just compare two strings with a forward slash in each. For some odd reason it throws that error.

**Comment by mokkabonna** [comment]
I am also seeing some strange behaviour here, and as @atifsyedali mentioned it seems to be related to slashes, maybe.. It seems several character are making this go bad, not sure which one. Can't get real consistent result it seems..

I have this string:

`git+ssh://git@github.my.corp.no:pet/grunt-pet-app.git#v0.8.1` and try to compare it to `git+ssh://git@github.my.corp.no:pet/grunt-pet-app.git#v0.8.2` 

This fails with the error "text diff_match_patch library" If i compare the first string to foo it is fine. Have tried removing different parts of the second string, but can't make sens of the results.

**Comment by MJefferson** [comment]
So this is clearly an issue for multiple people and in multiple environments, e.g. jspm. @benjamine, do you want me to open a PR to fix this?

**Comment by benjamine** [comment]
@MJefferson sure, although I think there are different issues mentioned on this thread, just consider:
- diffmatchpatch is intentionally excluded from the bundle, it's a big library that many users won't need. you have to either load it independently or use the "full" bundle included in the /public folder.
- I'm happy with support for jspm (and others) as soon as browserify support is not affected.

**Comment by mokkabonna** [comment]
Am I correct in my assumption that this happens when you decide to do a patch diff instad of a full diff? 

Does there exist any option to not use patch diff? Could it fall back to normal diff if this option is off?

Here is how I use this
```js
var delta = jsondiffpatch.diff(origContent.content, newFileContent);
formatters.html.hideUnchanged();
formatters.html.format(delta, origContent.content);
```

Why does this trigger loading diff_match_patch ? Is it the formatter?

**Comment by benjamine** [comment]
no, this is independant of formatting.
diffmatchpatch is a lib used when somewhere in the diff process there are 2 long strings (how long is determined by options.textDiff.minLength, defaults to `60`), when that happens that lib is used to generate an unidiff (a standard type of string diff),
on patch() the lib is used when a unidiff is found in the delta.
if you're not interested on it you can set options.textDiff.minLength to `Number.MAX_VALUE` (and jsondiffpatch will never try to find diffmatchpatch).

**Comment by MJefferson** [comment]
I think given that when it tries to fallback on diffmatchpatch, creating problems for many users, it might make sense to just make `Number.MAX_VALUE` the default `textDiff.minLength`.

I think most people install this lib for jsondiffpatch, and have no clue/concern for the text diff lib. (And like you said, it's not included in the bundle because most users won't need it.)

**Comment by atifsyedali** [comment]
So I was clueless about the diffmatchpatch. Including it in my build now makes everything work again. I think some warning about this in the readme file would be great at the very least. A better fix might be to just check for diffmatchpatch, and if it is present, use the current textDiff.minLength, and if it is not present, then set textDiff.minLength = Number.MAX_VALUE as @MJefferson suggested.

**Comment by benjamine** [comment]
@atifsyedali I think I like that, it might be a silent fail for people not loading diffmatchpatch in the browser, but it still works automatically for everyone else:
- browser with full bundle
- browser with diffmatchpatch loaded independently
- node.js
they will still benefit from text diff (because this means smaller payloads and less patch conflicts) without having to turn it on explicitly.
the only gotcha is, if you receive a delta that has a textdiff (because for example you generated that server-side where diffmatchpatch is loaded), and diffmatchpatch isn't loaded in your browser, you'd still get an error, but  I think that's a good thing.

**Comment by benjamine** [comment]
@atifsyedali done, from v0.1.38 if diff_match_patch cannot be found it will fallback to a regular string replace without erroring.

**Comment by atifsyedali** [comment]
Thanks!

**Pull request closed without merging**
