### PR TITLE
Added `move` op to jsonpatch, resolving #188

### PR DESCRIPTION
**Pull request by aryelu**
Added some docs, resolving #183

### CODE REVIEW

**Comment by benjamine** [comment]
sorry, I think the move to ES7 at v0.3.2 causes a lot of conflicts with this code, but wanted to get that migration finished (wepback, rollup, eslint, etc.).

- `/public/build` is gone (not needed anymore 🎉 , bundles are only included in npm, not in git
- now you can use ES7 (yay!), and I'm enforcing a few rules with eslint, eg. use `const`

so the code here seems it should be mostly unaffected. conflicts should be solved automatically, or be trivial, but let me know otherwise and I can help resolving them 👍

**Comment by aryelu** [comment]
Good job with the migration, I've updated the commit to es6

**Comment by benjamine** [comment]
nice! looks great, thanks!

**Comment by benjamine** [comment]
released as jsondiffpatch@0.3.5

**Pull request merged**
